# ------------------------------------------------------------------------------
# Build.yml
# ------------------------------------------------------------------------------

name: Build

on:
  push:
  pull_request:
    branches-ignore:
      - master
      - main
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build/build.cmd'
        run: ./build/build.cmd --root ./build
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          SignFile: ${{ secrets.SIGN_FILE }}
          SignPassword: ${{ secrets.SIGN_PASSWORD }}
          InstallationFiles: ${{ secrets.INSTALLATION_FILES }}